### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Elienock** [BankSinatra/Wordle#1]
This isn't an issue with the code, I've been following and I am trying to implement it using Java , is it possible to explain what each method does in the gameFragment class and GameViewModel

**Comment by BankSinatra** [comment]
The game fragment is just where the view is held. If you wanted to put the code in the fragment in the main activity file, it would be fine. The game ViewModel holds the data and does complex calculations for the entire game. It holds live data variables that are observed by the fragment and depending on the value of the fragment, the fragment properties will change
